# TCL File Generated by Component Editor 21.1
# Thu Nov 23 15:59:49 MSK 2023
# DO NOT MODIFY


# 
# beeper "beeper" v1.0
#  2023.11.23.15:59:49
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module beeper
# 
set_module_property DESCRIPTION ""
set_module_property NAME beeper
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME beeper
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL buzzer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file buzzer.vhd VHDL PATH components/buzzer.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter CLK_FREQ_HZ INTEGER 50000000
set_parameter_property CLK_FREQ_HZ DEFAULT_VALUE 50000000
set_parameter_property CLK_FREQ_HZ DISPLAY_NAME CLK_FREQ_HZ
set_parameter_property CLK_FREQ_HZ TYPE INTEGER
set_parameter_property CLK_FREQ_HZ UNITS None
set_parameter_property CLK_FREQ_HZ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CLK_FREQ_HZ HDL_PARAMETER true
add_parameter FREQ_HI INTEGER 50000
set_parameter_property FREQ_HI DEFAULT_VALUE 50000
set_parameter_property FREQ_HI DISPLAY_NAME FREQ_HI
set_parameter_property FREQ_HI TYPE INTEGER
set_parameter_property FREQ_HI UNITS None
set_parameter_property FREQ_HI ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FREQ_HI HDL_PARAMETER true
add_parameter FREQ_LO INTEGER 100000
set_parameter_property FREQ_LO DEFAULT_VALUE 100000
set_parameter_property FREQ_LO DISPLAY_NAME FREQ_LO
set_parameter_property FREQ_LO TYPE INTEGER
set_parameter_property FREQ_LO UNITS None
set_parameter_property FREQ_LO ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FREQ_LO HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset en reset_n Input 1


# 
# connection point comp
# 
add_interface comp conduit end
set_interface_property comp associatedClock clock
set_interface_property comp associatedReset reset
set_interface_property comp ENABLED true
set_interface_property comp EXPORT_OF ""
set_interface_property comp PORT_NAME_MAP ""
set_interface_property comp CMSIS_SVD_VARIABLES ""
set_interface_property comp SVD_ADDRESS_GROUP ""

add_interface_port comp HI hi Input 1
add_interface_port comp LO lo Input 1


# 
# connection point beep
# 
add_interface beep conduit end
set_interface_property beep associatedClock clock
set_interface_property beep associatedReset reset
set_interface_property beep ENABLED true
set_interface_property beep EXPORT_OF ""
set_interface_property beep PORT_NAME_MAP ""
set_interface_property beep CMSIS_SVD_VARIABLES ""
set_interface_property beep SVD_ADDRESS_GROUP ""

add_interface_port beep beeper buzzer Output 1

