# TCL File Generated by Component Editor 21.1
# Mon Nov 27 14:56:26 MSK 2023
# DO NOT MODIFY


# 
# display "display" v1.0
#  2023.11.27.14:56:26
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module display
# 
set_module_property DESCRIPTION ""
set_module_property NAME display
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME display
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL segment_7
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file segment_7.vhd VHDL PATH components/segment_7.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter CLK_FREQ_HZ INTEGER 50000000
set_parameter_property CLK_FREQ_HZ DEFAULT_VALUE 50000000
set_parameter_property CLK_FREQ_HZ DISPLAY_NAME CLK_FREQ_HZ
set_parameter_property CLK_FREQ_HZ TYPE INTEGER
set_parameter_property CLK_FREQ_HZ UNITS None
set_parameter_property CLK_FREQ_HZ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CLK_FREQ_HZ HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset en reset_n Input 1


# 
# connection point data_7seg
# 
add_interface data_7seg conduit end
set_interface_property data_7seg associatedClock clock
set_interface_property data_7seg associatedReset reset
set_interface_property data_7seg ENABLED true
set_interface_property data_7seg EXPORT_OF ""
set_interface_property data_7seg PORT_NAME_MAP ""
set_interface_property data_7seg CMSIS_SVD_VARIABLES ""
set_interface_property data_7seg SVD_ADDRESS_GROUP ""

add_interface_port data_7seg in_data data_7seg Input 8
add_interface_port data_7seg data_frac data_fractional Input 3


# 
# connection point segment
# 
add_interface segment conduit end
set_interface_property segment associatedClock clock
set_interface_property segment associatedReset reset
set_interface_property segment ENABLED true
set_interface_property segment EXPORT_OF ""
set_interface_property segment PORT_NAME_MAP ""
set_interface_property segment CMSIS_SVD_VARIABLES ""
set_interface_property segment SVD_ADDRESS_GROUP ""

add_interface_port segment seg7_code readdata Output 8


# 
# connection point sel_dig
# 
add_interface sel_dig conduit end
set_interface_property sel_dig associatedClock clock
set_interface_property sel_dig associatedReset reset
set_interface_property sel_dig ENABLED true
set_interface_property sel_dig EXPORT_OF ""
set_interface_property sel_dig PORT_NAME_MAP ""
set_interface_property sel_dig CMSIS_SVD_VARIABLES ""
set_interface_property sel_dig SVD_ADDRESS_GROUP ""

add_interface_port sel_dig dig_sel digit Output 4


# 
# connection point run_stop
# 
add_interface run_stop conduit end
set_interface_property run_stop associatedClock clock
set_interface_property run_stop associatedReset reset
set_interface_property run_stop ENABLED true
set_interface_property run_stop EXPORT_OF ""
set_interface_property run_stop PORT_NAME_MAP ""
set_interface_property run_stop CMSIS_SVD_VARIABLES ""
set_interface_property run_stop SVD_ADDRESS_GROUP ""

add_interface_port run_stop run go_run Input 1


# 
# connection point crutches
# 
add_interface crutches conduit end
set_interface_property crutches associatedClock clock
set_interface_property crutches associatedReset reset
set_interface_property crutches ENABLED true
set_interface_property crutches EXPORT_OF ""
set_interface_property crutches PORT_NAME_MAP ""
set_interface_property crutches CMSIS_SVD_VARIABLES ""
set_interface_property crutches SVD_ADDRESS_GROUP ""

add_interface_port crutches d1 d1 Output 8
add_interface_port crutches d2 d2 Output 8

